### ISSUE TITLE
Dynamic Linking Error

### ISSUE THREAD

**Issue by andoruB** [Draivin/XNBNode#3]
I'm getting this error while trying to run the app on a Windows 7 x86 install:

```
Error: Dynamic Linking Error: Win32 error 126
    at new DynamicLibrary (Z:\bin\Stardew Valley\XNBNode-master\node_modules\ffi\lib\dynamic_library.js:74:11)
    at new Library (Z:\bin\Stardew Valley\XNBNode-master\node_modules\ffi\lib\library.js:45:12)
    at Object.<anonymous> (Z:\bin\Stardew Valley\XNBNode-master\compress.js:25:17)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (Z:\bin\Stardew Valley\XNBNode-master\converter.js:6:16)
```

**Comment by draivin** [comment]
This seems like an error related to the required dll not being there, looking at the readme right now, it seems that the link to where you could find the dll broke, the dll is called `xcompress32.dll`, if you're able to find it on the net please post a comment here with a link and I'll update the readme.

**Comment by andoruB** [comment]
I've found it in the XNB Mod Toolkit (http://community.playstarbound.com/threads/modding-guides-and-general-modding-discussion-redux.109131/page-6#post-2837587) that includes your utility, and I uploaded it: https://mega.nz/#!XZlBmLbI!8kJZ9fdTD2-CxVHg8Zs_n2S18OO2rpEcA6BRdyCCoTo

I would suggest making multiple mirrors of this file.

**Comment by jwg4** [comment]
Where do you save the dll to?
